language: node_js
node_js:
  - lts/*
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.pkg-cache
before_deploy: yarn pkg
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: pkg/*
  skip_cleanup: true
  on:
    repo: yuta0801/factorio-mods-sync
    tags: true
